### ISSUE TITLE
Issue with escaping and globs

### ISSUE THREAD

**Issue by newodahs** [markuskont/go-sigma-rule-engine#13]
Found while testing some sigma rules that were part of a `contains` modified group and had a leading backslash.

Basically, the Sigma rules for escaping are different enough from the glob library to cause us to throw out things like singular backslashes.

See: https://github.com/newodahs/go-sigma-rule-engine/issues/5

I have a fix for this already, just cleaning it up and making sure testing is in place.

**Comment by newodahs** [comment]
Fixed with Pull Request https://github.com/markuskont/go-sigma-rule-engine/pull/14

Also found that there was some additional escaping needed for the square and curly brackets, see pull request notes.

**Comment by markuskont** [comment]
Glad you caught it, merged.
