### ISSUE TITLE
how to read local logs for simple steamer

### ISSUE THREAD

**Issue by gen3111620** [markuskont/go-sigma-rule-engine#29]
Hi, I am a golang newbie

I want to use the repo implement read windows event log and mapping sigma rule,

in this case, I think may mapping this sigma rule "[proc_creation_win_wmic_recon_group](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_recon_group.yml)", but met some problem when use examples/simple-steamer main.go 

compile
```
type data.json | go run main.go

```

example data.json, just input 2 keys
```json
{
**"CommandLine" : "powershell.exe -ExecutionPolicy Bypass -C wmic.exe group get name\"**
**"OriginalFileName": "wmic.exe"**
...
}
```
 error message like this as below : 

![image](https://user-images.githubusercontent.com/31429532/225185945-4706f07d-cbd1-4487-8219-8a8a3dfab37b.png)

**Comment by gen3111620** [comment]
I have edit some code and worked as belows, it can mapping results, but I think this convert this method thn

after switching the method as below, the sigma rule was detected, but I think this loses the meaning of streammer stdin, so the original problem still exists.


```go
data := `{"CommandLine" : "powershell.exe -ExecutionPolicy Bypass -C \"wmic.exe group get name\"","OriginalFileName": "wmic.exe"}`
scanner := bufio.NewScanner(strings.NewReader(data))
```
![image](https://user-images.githubusercontent.com/31429532/225187526-db783b01-febd-4e49-9a50-9f45f74932d2.png)


I have others question, if have a json file contains lots of event log,
1. how can I read the json and work in this code? 
2. how to implement the original method(stdin) to mapping sigma rule?
thanks

**Comment by gen3111620** [comment]
final i try to edit this code then can read json file and detect sigma rules, and provide the code as belows,
```go
package main

import (
	"encoding/json"
	"flag"
	"io/ioutil"
	"log"
	"os"
	"strings"

	"github.com/markuskont/datamodels"
	"github.com/markuskont/go-sigma-rule-engine"
)

var (
	flagRuleSetPath = flag.String("path-ruleset", "./windows/", "Root folders for Sigma rules. Semicolon delimits paths.")
)

func main() {
	flag.Parse()
	if *flagRuleSetPath == "" {
		log.Fatal("ruleset path not configured")
	}
	ruleset, err := sigma.NewRuleset(sigma.Config{
		Directory:       strings.Split(*flagRuleSetPath, ";"),
		NoCollapseWS:    false,
		FailOnRuleParse: false,
		FailOnYamlParse: false,
	})
	if err != nil {
		log.Fatal(err)
	}
	data, err := ioutil.ReadFile("data.json")

	if err != nil {
		log.Fatal(err)
	}

	var events []map[string]interface{}

	if err := json.Unmarshal([]byte(data), &events); err != nil {
		panic(err)
	}

	output := os.Stdout
	for _, event := range events {
		jsonStr, err := json.Marshal(event)
		if err != nil {
			log.Println(err)
		}

		var obj datamodels.Map
		if err := json.Unmarshal(jsonStr, &obj); err != nil {
			log.Println(err)
		}

		if results, ok := ruleset.EvalAll(obj); ok && len(results) > 0 {
			obj["sigma_results"] = results
			encoded, err := json.Marshal(obj)
			if err != nil {
				log.Println(err)
			}
			output.Write(encoded)
		}

	}

}

```

fake test data.json
```json
[{
"EventID": "4",
"CommandLine" : "powershell.exe -ExecutionPolicy Bypass -C wmic.exe group get name",
"OriginalFileName": "wmic.exe"
},
{
    "EventID": "4",
    "CommandLine" : "powershell.exe -ExecutionPolicy Bypass -C wmic.exe group get name",
    "OriginalFileName": "wmic.exe"
}
]
```

output

![image](https://user-images.githubusercontent.com/31429532/225195443-8cedbff8-a213-4ff0-a4aa-ce5e9d624c8e.png)

**Comment by markuskont** [comment]
Sorry for missing this. Yea, it looks like the json file you had has the document pretty printed. This breaks go scanner since it presents individual lines to JSON parser. I believe you simply need a file with each JSON doc on separate line. So it should be something like this:

```
{"CommandLine" : "powershell.exe -ExecutionPolicy Bypass -C wmic.exe group get name", "OriginalFileName": "wmic.exe"}
{"CommandLine" : "powershell.exe -ExecutionPolicy Bypass -C wmic.exe group get name", "OriginalFileName": "wmic.exe"}
{"CommandLine" : "powershell.exe -ExecutionPolicy Bypass -C wmic.exe group get name", "OriginalFileName": "wmic.exe"}
```

See: http://dataprotocols.org/ndjson/

**Comment by markuskont** [comment]
Also, please feel free to PR your modified example to main repo :)
